# Generated by Django 3.2.6 on 2021-08-29 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('founders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('founder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='founders.founder')),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investor')),
            ],
        ),
    ]
